<Project Sdk="Godot.NET.Sdk/4.3.0">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
    <BackdashVersion>0.6.12-preview</BackdashVersion>
    <BackdashGnsVersion>0.1.0-alpha.3</BackdashGnsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Backdash.Utils" Version="$(BackdashVersion)" />
    <!-- Copy `steam_appid.txt` for ease of testing, should NOT do this in production! -->
    <Content Include="steam_appid.txt">
      <CopyToOutputDirectory>IfDifferent</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <!-- Backdash.Gns for each platform -->
  <Choose>
    <!-- Windowns AMD64 -->
    <When Condition="$([System.Text.RegularExpressions.Regex]::IsMatch($(DefineConstants), '^(.*;)*GODOT_WINDOWS(;.*)*$'))">
      <ItemGroup>
        <PackageReference Include="Backdash.Gns.Steamworks.Win64" Version="$(BackdashGnsVersion)" />
        <ContentWithTargetPath Include="native-libs/win64/*.dll">
          <CopyToOutputDirectory>IfDifferent</CopyToOutputDirectory>
          <TargetPath>%(Filename)%(Extension)</TargetPath>
        </ContentWithTargetPath>
      </ItemGroup>
    </When>
    <!-- Linux AMD64 -->
    <When Condition="$([System.Text.RegularExpressions.Regex]::IsMatch($(DefineConstants), '^(.*;)*GODOT_LINUXBSD(;.*)*$'))">
      <ItemGroup>
        <PackageReference Include="Backdash.Gns.Steamworks.Posix64" Version="$(BackdashGnsVersion)" />
        <ContentWithTargetPath Include="native-libs/linux64/*.so">
          <CopyToOutputDirectory>IfDifferent</CopyToOutputDirectory>
          <TargetPath>%(Filename)%(Extension)</TargetPath>
        </ContentWithTargetPath>
      </ItemGroup>
    </When>
    <!-- macOS AArch64 -->
    <When Condition="$([System.Text.RegularExpressions.Regex]::IsMatch($(DefineConstants), '^(.*;)*GODOT_OSX(;.*)*$'))">
      <ItemGroup>
        <PackageReference Include="Backdash.Gns.Steamworks.Posix64" Version="$(BackdashGnsVersion)" />
        <ContentWithTargetPath Include="native-libs/osx/*.dylib">
          <CopyToOutputDirectory>IfDifferent</CopyToOutputDirectory>
          <TargetPath>%(Filename)%(Extension)</TargetPath>
        </ContentWithTargetPath>
      </ItemGroup>
    </When>
  </Choose>
</Project>
